[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "concatenative-synth"
version = "0.1.0"
description = "A command-line tool for concatenative audio synthesis"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
  { name = "Matthew Harris", email = "matthewh806@gmail.com" },
]

dependencies = [
    "numpy",
    "soundfile",
    "librosa",
    "yt-dlp",
    "freesound-python",
    "scipy",
    "sounddevice"
]

[project.optional-dependencies]
dev = [
  "pytest",
]

[tool.pytest.ini_options]
min_version = 6.0
addopts = "--import-mode=append --strict-markers"

pythonpath = ["src"]
testpaths = ["tests"]

python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[project.scripts]
# This creates the 'concat-synth' command and points it to the
# 'main' function inside the 'cli.py' file.
concat-synth = "concatenative.cli:main"

