[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "concatenative-synth"
version = "0.1.0"
description = "A command-line tool for concatenative audio synthesis"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
  { name = "Matthew Harris", email = "matthewh806@gmail.com" },
]

dependencies = [
    "numpy",
    "soundfile",
    "librosa",
    "yt-dlp",
    "freesound-python",
]

[project.scripts]
# This creates the 'concat-synth' command and points it to the
# 'main' function inside the 'cli.py' file.
concat-synth = "concatenative.cli:main"

